image:
  file: .gitpod.Dockerfile
ports:
  - port: 8787
    onOpen: open-browser
tasks:
  - init: echo "R_LIBS_USER=/home/gitpod/libs" >> /home/gitpod/.Renviron
  - command: sudo chmod 777 /var/lib/rstudio-server/rstudio-os.sqlite && /usr/lib/rstudio-server/bin/rserver --server-user gitpod
