image:
  file: .gitpod.Dockerfile
tasks:
  - init: echo "R_LIBS_USER=/home/gitpod/libs" >> /home/gitpod/.Renviron
  - command: sudo /usr/lib/rstudio-server/bin/rserver --server-user=gitpod --server-working-dir=/workspace --server-daemonize=1
ports:
  - port: 8787
    onOpen: open-browser
